var jQuery = require('jquery');
require('./alert.js');
require('./button.js');
require('./carousel.js');
require('./collapse.js');
require('./dropdown.js');
require('./modal.js');
require('./tooltip.js');
require('./popover.js');
require('./scrollspy.js');
require('./tab.js');
require('./affix.js');
module.exports = require('jquery');
